### ISSUE TITLE
Merging features into ndppd

### ISSUE THREAD

**Issue by john-sharratt** [google/ndprbrd#10]
Hi

I found your use case very useful and appreciate the efforts you put into this as it certainly saved me heaps of time.

After some effort I found that the functionality while still effective as a separate daemon may be a bit easier to maintain if merged with the original NDP proxy daemon - hence I forked the ndppd project and added the ability to automatically create routes in the project ndppd.

It's still a fork but I thought you may be interested in it, if so please take a look and let me know.
https://github.com/john-sharratt/ndppd

The pull request I've made in the NDPPD project is here:
https://github.com/DanielAdolfsson/ndppd/pull/30

Kind Regards
John

**Comment by DarthGandalf** [comment]
That's great! To not have too many threads, I'll reply more on DanielAdolfsson/ndppd#30
