### ISSUE TITLE
another NDP proxy implement call for try

### ISSUE THREAD

**Issue by congzhangzh** [google/ndprbrd#11]
Hi folks,

I built another NDP proxy by python and scapy, hope you guys like it and give a try.

https://github.com/congzhangzh/andpp

Btw, it works 4 me

Tks,
Cong

**Comment by DarthGandalf** [comment]
Erm, good to know, I guess?

The very first commit in this repo was also python with scapy, before I decided to rewrite it on C++ to be able to run on devices where there's no python
