### ISSUE TITLE
Problem with route deletion

### ISSUE THREAD

**Issue by DarthGandalf** [google/ndprbrd#9]
From #8 by @dulemis

> On my Linux gateway the routes are never deleted, when running ndprbrd interactively in the shell I see messages like "deleting XXX:XXX:XXX from brX" but when issuing "ip -6 route" this route is still there. I have changed the expiration to 10s and the routes are still there, even if the client is disconnected. So old and stale routes are stacking up, also leading to the next problem.

**Comment by DarthGandalf** [comment]
That isn't supposed to happen... It worked fine for me when I was using ndprbrd.

When deleting a route, it calls `ip -6 route del XXX:XXX:XXX dev brX protocol NN`, where NN is 100 by default. What happens if you run this command by hand? How does the route look like?

When this gets fixed, also need to add the test to travis.

**Comment by dulemis** [comment]
Hello!

Okey, so I tried it now. Connected my phone to one SSID (interface bridged to br0), then changed to another SSID on the same router (bridged to br1)

Br0
2001:2002:5ae1:c206:XXX:XXX dev br0  proto 100  metric 1024  mtu 1500 advmss 1440 hoplimit 0

Br1
2001:2002:5ae1:c206:XXX:XXX dev br0  proto 100  metric 1024  mtu 1500 advmss 1440 hoplimit 0
2001:2002:5ae1:c206:XXX:XXX dev br1  proto 100  metric 1024  mtu 1500 advmss 1440 hoplimit 0

I'm running the daemon with --expire=10 just to test. Unfortunately the old, br0 route doesn't get deleted.

When I manually run the ip -6 route del command, I just noticed I have to run it three times to delete the route...? Maybe that is what's causing this issue.
I looked through the source code, changed  ip -6 route del to ip -6 route flush, recompiled and now it seems to work for me.

Strange, I'm not sure why this is?
I also can't seem to find what the difference is between "del" and "flush" command, other than that when I tried "flush" it deletes the route directly.

**Comment by DarthGandalf** [comment]
Does anything in `ip -6 route show` change after first two `del` commands?

According to https://stackoverflow.com/questions/19663727/ip-route-del-does-not-delete-entire-table `flush` deletes all matched routes, and `del` deletes first one.
But I don't see how the same route can be there several times on the same interface.

**Comment by dulemis** [comment]
No, not until the third delete. It's like you say, strange that the same route is added several times!
